@startuml ActView account statistic
skin rose
!pragma useVerticalIf on
scale 3

title "View account statistic"

|Admin|
|UI|
start
    :1. Show home page;
    |Admin|
    :2. Access statistic page;
    |UI|
    :3. Send get request for api;
    |Account controller|
    :4. Resolve the request and send it to service;
    |Account service|
    :5. Asking repository for List Account data;
    |Account repository|
    :6. Access database;
    :7. Query data by id;
    :8. Return object;
    |Account service|
    :9. Caculate the information \n(number of user,\n user created in month, etc..);
    :10. Return information;
    |Account controller|
    :11. Return request result, include body;
    |UI|
    :12. Manipulate request and show;
stop




@enduml