@startuml 4.2 View order list
skin rose
!pragma useVerticalIf on
scale 3

title "View order list"

|Admin|
|UI|
start
    :1. Show home page;
    |Admin|
    :2. Access order page;
    |UI|
    :3. Send get request for api;
    |Order controller|
    :4. Resolve the request and send it to service;
    |Order service|
    :5. Asking repository for data;
    |Order repository|
    :6. Access database;
    :7. Query select all data;
    :8. Return object list;
    |Order service|
    :9. Return object list;
    |Order controller|
    :10. Return request result, include body;
    |UI|
    :11. Manipulate request and show;
stop




@enduml