@startuml ActCreateCategory

skin rose
scale 3

|Admin|
|User\nInterface|
|Category\nController|
|Category\nService|
|Category\nRepository|
|User\nInterface|
start
:1. Display category\ndetail page;
|Admin|
:2. Click "Update" button;
|User\nInterface|
repeat
:3. Display category\ninformation form;
|Admin|
:4. Enter category\ninformation;
:5. Click "Update" button;
|User\nInterface|
:6. Request update\ncategory;
|Category\nController|
:7. Request update\ncategory;
|Category\nService|
:8. Check category\ninformation;
backward :9.1.Return\nerror message;
repeat while(Category information\nis valid) is(no) not(yes)
:9.2. Update category;
|Category\nRepository|
:10. Access database;
:11. Query insert;
:12. Return category;
|Category\nService|
:13. Return result message;
|Category\nController|
:14. Return result message;
|User\nInterface|
:15. Display result message;
stop

@enduml