@startuml ActViewCategoryStatistic

skin rose
scale 3

|Admin|
|User\nInterface|
|Category Statistic\nController|
|Category Statistic\nService|
|Category\nRepository|
|User\nInterface|
start
:1. Display\ncategory list;
|Admin|
:2. Click\n"Show statistic" button;
|User\nInterface|
:3. Request\nstatistic metrics;
|Category Statistic\nController|
:4. Request\nstatistic metrics;
|Category Statistic\nService|
:5. Get all\ncategory info;
|Category\nRepository|
:6. Access database;
:7. Query select;
:8. Return\ncategory list;
|Category Statistic\nService|
:9. Calculate\nstatistic metrics;
:10. Return\nstatistic metrics;
|Category Statistic\nController|
:11. Return\nstatistic metrics;
|User\nInterface|
:12. Display\nstatistic metrics;
stop

@enduml