@startuml GeneralUsecase
skin rose
scale 3

left to right direction

actor Admin as admin
actor Customer as customer
actor Staff as staff

rectangle "Harbe Ecomerce" {
    usecase (Manage product) as qlsp
    usecase (Manage cart) as qlgh
    usecase (Manage category) as qldmsp
    usecase (Manage order) as qlddh
    usecase (Manage account) as qlnd
    usecase (Manage voucher) as qlmgg
    usecase (Manage notification) as qltb
    usecase (Sign in) as dn
    usecase (Sign up) as dk
}

admin --- qlsp
admin --- qldmsp
admin --- qlddh
admin --- qlnd
admin --- qlmgg
admin --- dn
admin --- qltb

qlsp --- customer
qlgh --- customer
qldmsp --- customer
qlddh --- customer
qlmgg --- customer
dn --- customer
dk --- customer
qltb --- customer

staff - qlsp
staff --- qlddh
staff --- dn
staff --- qltb


@enduml