@startuml ManageProduct

left to right direction
scale 3
skin rose

actor Admin as admin
actor Customer as customer
actor Staff as staff

rectangle "Manage product" {
    usecase (Add product) as tsp
    usecase (View product list) as xdssp
    usecase (View product info) as xttsp
    usecase (Update product info) as sttsp
    usecase (Delete product) as xosp
    usecase (Filter prduct) as lsp
    usecase (Search product) as tksp
    usecase (View product statistics) as xtk
    usecase (Export product list) as xudssp
}

admin --- tsp
admin --- xttsp
admin --- xosp
admin --- sttsp
admin --- lsp
admin --- tksp
admin --- xtk
admin --- xudssp

xttsp --- customer
lsp --- customer
tksp --- customer

staff --- xttsp
staff --- lsp
staff --- tksp

tsp <... xdssp : <<include>>
xttsp <... xdssp : <<include>>
lsp <... xdssp : <<include>>
tksp <... xdssp : <<include>>
xudssp <... xdssp : <<include>>

@enduml