@startuml ManageCart

left to right direction
scale 3
skin rose

actor Customer as customer

rectangle "Manage cart" {
    usecase (Add product to cart) as tspvgh
    usecase (View total price) as xtgt
    usecase (View basic product info) as xttcbcsp
    usecase (Update product quantity) as sslsp
    usecase (Delete product in cart) as xsptrgh
    usecase (Delete all products in the cart) as xttcsptrgh
}

customer --- tspvgh
customer --- xtgt
customer --- xttcbcsp
customer --- sslsp
customer --- xsptrgh
customer --- xttcsptrgh

@enduml