@startuml ManageCategory

left to right direction
scale 3
skin rose

actor Admin as admin
actor Customer as customer
actor Staff as staff

rectangle "Manage category" {
    usecase (Create category) as tdm
    usecase (View category list) as xdsdm
    usecase (Update category) as sttdm
    usecase (Delete category) as xodm
}

admin --- tdm   
admin --- xodm
admin --- sttdm

customer --- xdsdm

staff --- xdsdm

tdm <.. xdsdm : <<include>>
sttdm <.. xdsdm : <<include>>
xodm <.. xdsdm : <<include>>

@enduml