@startuml ManageCategory

left to right direction
scale 3
skin rose

actor Admin as admin
actor Customer as customer
actor Staff as staff

rectangle "Quản lí danh mục sản phẩm" {
    usecase (Thêm danh mục) as tdm
    usecase (Xem danh sách danh mục) as xdsdm
    usecase (Xem thông tin danh mục) as xttdm
    usecase (Xuất danh sách danh mục) as xudsdm
    usecase (Xóa danh mục) as xodm
    usecase (Sửa thông tin danh mục) as sttdm
    usecase (Xem thống kê) as xtk
    usecase (Xem thống kê số lượng sản phẩm\ntheo danh mục) as tkslsptdm
    usecase (Xem thống kê doanh thu\ntừ danh mục) as tkdttdm
    usecase (Xem Thống kê số lượt bán\ntheo danh mục) as tkslbtdm
}

admin --- tdm   
admin --- xttdm
admin --- xudsdm
admin --- xodm
admin --- sttdm
admin --- xtk

customer --- xttdm

staff --- xttdm

xtk ..> tkslsptdm : <<extend>>
xtk ..> tkdttdm : <<extend>>
xtk ..> tkslbtdm : <<extend>>

tdm <.. xdsdm : <<include>>
xttdm <.. xdsdm : <<include>>
xudsdm <.. xdsdm : <<include>>

@enduml