@startuml ManageUser

left to right direction
scale 3
skin rose

actor Admin as admin

rectangle "5. Quản lý người dùng" {
    usecase (Tìm kiếm tài khoản) as tktk
    usecase (Tạo tài khoản) as ttk
    usecase (Xem danh sách tài khoản) as xdstk
    usecase (Xem thông tin tài khoản) as xtttk
    usecase (Sửa thông tin tài khoản) as scttk
    usecase (Xóa tài khoản ) as xtk
    usecase (Báo cáo thống kê\nsố lượng tài khoản đang tồn tại) as bctksltkdtt
    usecase (Báo cáo doanh thu\ncủa từng tài khoản) as bcdtcttk
}

admin --- ttk
admin --- xtttk
admin --- scttk
admin --- xtk
admin --- tktk
admin --- bctksltkdtt
admin --- bcdtcttk

ttk <.. xdstk : <<include>>
xtttk <.. xdstk : <<include>>
tktk <.. xdstk : <<include>>

@enduml