@startuml ManageNotification

skin rose
scale 3

left to right direction

actor Admin as admin
actor Customer as customer
actor Staff as staff

rectangle "7. Quản lí thông báo" {
    usecase (Thêm thông báo) as ttb
    usecase (Xem danh sách thông báo) as xdstb
    usecase (Xem thông tin thông báo) as xtttb
    usecase (Sửa thông báo) as stb
    usecase (Xóa thông báo) as xtb
}

admin --- ttb
admin --- xtttb
admin --- stb
admin --- xtb

staff --- xtttb

customer --- xtttb

ttb <.. xdstb : <<inlude>>
xtttb <.. xdstb : <<include>>

@enduml