@startuml ActView notification
skin rose
!pragma useVerticalIf on
scale 3

title "View notification"

|User|
|UI|
start
    :1. Show list notification page;
    |User|
    :2. Access notificaiton info;
    |UI|
    :3. Send get request for api;
    |Notification controller|
    :4. Resolve the request and send it to service;
    |Notification service|
    :5. Asking repository for data;
    |Notification repository|
    :6. Access database;
    :7. Query data by id;
    :8. Return object;
    |Notification service|
    :9. Return object;
    |Notification controller|
    :10. Return request result, include body;
    |UI|
    :11. Manipulate request and show;
stop




@enduml