@startuml ActDelete notification
skin rose
!pragma useVerticalIf on
scale 3

title "Delete notification"

|Admin|
|UI|
start
    :1. Show notification list;
    |Admin|
    :2. Choose list notification;
    |UI|
    :3. Show choosed option;
    |Admin|
    :4. Submit list notification to delete;
    |UI|
    :5. Send delete request api;
    |Notification controller|
    :6. Resolve the request and send it to service;
    |Notification service|
    :7. Push list notification need to delete;
    |Notification repository|
    :8. Access database;
    :9. Query delete;
    :10. Return result;
    |Notification service|
    :11. Return result;
    |Notification controller|
    :12. Return request result;
    |UI|
    :13. Show delete result;
stop




@enduml