@startuml ActViewProductList

skin rose
scale 3

|User|
|User\nInterface|
|Product\nController|
|Product\nService|
|Product\nRepository|
|User\nInterface|
start
:1. Display home page;
|User|
:2. Scroll down\nto view product list;
|User\nInterface|
:3. Request product list;
|Product\nController|
:4. Request product list;
|Product\nService|
:5. Get product list;
|Product\nRepository|
:6. Access database;
:7. Query select\nproduct list;
:8. Return product list;
|Product\nService|
:9. Return product list;
|Product\nController|
:10. Return product list;
|User\nInterface|
:11. Display product list;
stop

@enduml