@startuml 7. Create notification
skin rose
!pragma useVerticalIf on
scale 3

title "Create notification"

|Admin|
|UI|
start
    :Show create notification form;
    |Admin|
    :Submit new notification;
    |UI|
    :Send post request api;
    |Notification controller|
    :Resolve the request and send it to service;
    |Notification service|
    :Validate and push new data to repository;
    |Notification repository|
    :Access database;
    :Query insert;
    :Return result;
    |Notification service|
    :Return result;
    |Notification controller|
    :Return request result;
    |UI|
    :Show create result;
stop




@enduml