@startuml 7. Update notification
skin rose
!pragma useVerticalIf on
scale 3

title "Update notification"

|Admin|
|UI|
start
    :1. Show edit notification form;
    |Admin|
    :2. Submit updated edit form;
    |UI|
    :3. Send update request api;
    |Notification controller|
    :4. Resolve the request and send it to service;
    |Notification service|
    :5. Validate and push update data to repository;
    |Notification repository|
    :6. Access database;
    :7. Query update;
    :8. Return result;
    |Notification service|
    :9. Return result;
    |Notification controller|
    :10. Return request result;
    |UI|
    :11. Show update result;
stop




@enduml