@startuml ActSignUp

skin rose
scale 3

|Customer|
|User\nInterface|
|Authorization\nController|
|Authorization\nService|
|Application User\nRepository|
|Cart\nRepository|
|User\nInterface|
start
repeat
:1. Display sign up page;
|Customer|
:2. Enter infomation;
:3. Click "Sign up" button;
|User\nInterface|
:4. Send sign up request\nand information;
|Authorization\nController|
:5. Send sign up request\nand information;
|Authorization\nService|
:6. Check infomation format;
backward :7.1. Display error message;
repeat while (Information\nis valid?) is(no) not(yes)
:7.2. Hash password;
:8. Request account infomation\nby username;
|Application User\nRepository|
:8. Query account info\nby username;
:9. Return account info\nby username;
|Authorization\nService|
:10. Check username;
if () then (username already exist)
    :11.1. Return\nerror message;
    |Authorization\nController|
    :12.1. Retur\nerror message;
    |User\nInterface|
    :13.1. Display\nerror message;
    stop
else(infomation is valid)
    |Authorization\nService|
    :11.2. Create user\nwith information;
    |Application User\nRepository|
    :12.2. Save user\ninformation;
    :13.2. Return\nsuccess message;
    |Authorization\nService|
    :14. Create cart;
    |Cart\nRepository|
    :15. Save cart\ninformation;
    :16. Return\nsuccess message;
    |Authorization\nService|
    :17. Return\nsuccess message;
    |Authorization\nController|
    :18. Return\nsuccess message;
    |User\nInterface|
    :19. Display sign in page\nand success message;
    stop
@enduml