@startuml ActSignUp

skin rose
scale 3

|Customer|
|User\nInterface|
|Authorization\nController|
|Authorization\nService|
|Application User\nRepository|
|Cart\nRepository|
|User\nInterface|
start
repeat
:1. Display sign up page;
|Customer|
:2. Enter infomation;
:3. Click "Sign up" button;
|User\nInterface|
:4. Send sign up request\nand information;
|Authorization\nController|
:5. Send sign up request\nand information;
|Authorization\nService|
:6. Check infomation format;
backward :7.1. Display error message;
repeat while (Information\nis valid?) is(no) not(yes)
:7.2. Hash password;
:8. Request account infomation\nby username;
|Application User\nRepository|
:8. Access database;
:9. Query select account info\nby username;
:10. Return account info\nby username;
|Authorization\nService|
:11. Check username;
if () then (username already exist)
    :12.1. Return\nerror message;
    |Authorization\nController|
    :13.1. Retur\nerror message;
    |User\nInterface|
    :14.1. Display\nerror message;
    stop
else(infomation is valid)
    |Authorization\nService|
    :12.2. Create user\nwith information;
    |Application User\nRepository|
    :13.2. Access database;
    :14.2. Query insert user\nwith infomation;
    :15. Return\nsuccess message;
    |Authorization\nService|
    :16. Create cart;
    |Cart\nRepository|
    :17. Access database;
    :18. Query insert cart\nwith infomation;
    :19. Return\nsuccess message;
    |Authorization\nService|
    :20. Return\nsuccess message;
    |Authorization\nController|
    :21. Return\nsuccess message;
    |User\nInterface|
    :22. Display sign in page\nand success message;
    stop
@enduml