@startuml Class Diagram

skin rose
skinparam classAttributeIconSize 0
' skinparam linetype ortho
skinparam linetype polyline
hide circle
scale 3

' Product
class Product{
    - id: long
    - name: string
    - brand: string
    - url_key: string
    - description: string
    - price: double
    - discount_rate: double
    - thumbnail_url: string
    - images: List<string>
    - review_count: int
    - rating_average: double
    - quantity_sold: int
    - highlight: List<HighlightItem>
    - seller: Seller
    - supplier: Supplier
    - categories: List<Category>
    - product_specifications: List<ProductSpecification>
}

class Supplier{
    - id: long
    - name: string
}

class ProductSpecification{
    - id: long
    - name: string
    - value: string
    - product: Product
}

class ProductOption{
    - id: long
    - name: string
    - product: Product
}

class ProductCategory{
    - id: long
    - product: Product
    - category: Category
}

class ProductHighlight{
    - id: long
    - description: string
}

class Seller{
    - id: long
    - name: string
    - logo: string
    - slug: string
}

' Category
class Category{
    - id: long
    - name: string
    - url_key: string
    - thumbnail_url: string
    - parent_id: long
    - is_primary: boolean
}

' Review
class Review{
    - id: long
    - rating: int
    - title: string
    - content: string
    - product: Product
    - user: User
}

' User
class User{
    - id: long
    - name: string
    - email: string
    - phone: string
    - password: string
    - avatar: string
    - role: string
    - cart: Cart
    - addresses: List<Address>
    - reviews: List<Review>
    - orders: List<Order>
}

class Address{
    - id: long
    - name: string
    - phone: string
    - company: string
    - province: string
    - district: string
    - ward: string
    - address: string
    - address_type: string
    - is_default: boolean
    - user: User
}


' Cart
class Cart{
    - id: long
    - cart_details: List<CartDetail>
}

class CartDetail{
    - id: long
    - quantity: int
    - seller: Seller
    - cart: Cart
    - product: Product
}

' Order
class Order{
    - id: long
    - total: double
    - status: string
    - payment_method: string
    - payment_status: string
    - shipping_fee: double
    - note: string
    - created_at: datetime
    - address: Address
    - user: User
    - products: List<Product>
}

' Notification
class Notification{
    - id: long
    - title: string
    - content: string
    - created_at: datetime
}

Product "1" *-- "1..*" ProductSpecification
Product "1" *-- "1..*" ProductOption
Product "1..* "--* "1" Seller
Product "1" o-- "1..*" Supplier
Product "1" *-- "1..*" Review
Product "1..*" --o "1" Order
Product "1" *-- "1..*" ProductHighlight

ProductCategory "1" -- "1..*" Product
ProductCategory "1" -- "1..*" Category

User "1" *-- "1..*" Address
User "1" *-- "1..*" Review

Cart "1" --* "1..*" User
Cart "1" *-- "1..*" CartDetail

Order "1..*" --* "1" User
Order "1" -- "1..*" Address

@enduml